name = "bigstankytortilla"
author = "brody"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c06af5ce17f333d7c65ed3dc5e553f6d5c71d099fa978f20c95ed9be7dc44c63"

[versions]
forge = "43.2.13"
minecraft = "1.19.2"
